on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run:
    name: Upload vsix package
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: clean install dependencies
        run: npm ci
      - name: run vscode:prepublish
        run: npm run vscode:prepublish
      - name: run headless test
        uses: GabrielBB/xvfb-action@v1.6
        with:
          run: npm test
      - name: build vsix package
        run: npm run package
      - name: upload vsix package
        uses: actions/upload-artifact@v3
        with:
          path: veriloghdl-*.vsix
