on:
  workflow_dispatch:
    inputs:
      kind:
        description: 'Update kind (major, minor, patch)'
        default: 'patch'

name: Publish extension to marketplace
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm install -g @vscode/vsce
      - run: git config --global user.email "anolte5"12@gmail.com
      - run: git config --global user.name "Andrew Nolte"
        # Use vsce first- this will bump the version number
      - name: Publish to Visual Studio Marketplace
        run: vsce publish ${{ github.event.inputs.kind }} --pat ${{ secrets.VS_MARKETPLACE_TOKEN }}
      - run: npm install -g ovsx
      - name: Publish to Open Vsix
        run: npx ovsx publish --pat ${{ secrets.OPEN_VSX_TOKEN }}
      - run: git push
