on:
  workflow_dispatch:
    inputs:
      kind:
        description: 'Update kind (major, minor, patch)'
        default: 'patch'

name: Publish extension to marketplace
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm install -g @vscode/vsce
      - run: git config --global user.email "anolte5"12@gmail.com
      - run: git config --global user.name "Andrew Nolte"
      - name: Publish to Visual Studio Marketplace
        run: vsce publish ${{ github.event.inputs.kind }} --pat ${{ secrets.VS_MARKETPLACE_TOKEN }}
        run: git add .
        run: git commit -m "cut release"
        run: git push
      # - run: npm install -g ovsx
      # - name: Publish to Open Vsix
      #   run: npx ovsx publish -p ${{ secrets.OPEN_VSX_TOKEN }}
